services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: muaz
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-service:
    image: muazwazir1/eureka-service:latest
    container_name: eureka-service
    ports:
      - "8671:8761"
    depends_on:
      - zipkin

  api-gateway:
    image: muazwazir1/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    depends_on:
      - zipkin
      - eureka-service

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
